name: CI
on:
  push:
    branches: [ main ]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run JMeter Test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: ReqResInAPITest.jmx
          outputReportsFolder: reports/

